CREATE DATABASE SQL_Insights;
USE SQL_Insights;


CREATE TABLE Customers (
    Cust_ID INT PRIMARY KEY,
    Name VARCHAR(50),
    City VARCHAR(50),
    Email VARCHAR(100)
);

INSERT INTO Customers VALUES
(101,'Rahul Sharma','Hyderabad','rahul@gmail.com'),
(102,'Priya Reddy','Bangalore','priya@gmail.com'),
(103,'Amit Kumar','Delhi','amit@gmail.com'),
(104,'Sneha Patel','Mumbai','sneha@gmail.com'),
(105,'Arjun Rao','Chennai','arjun@gmail.com'),
(106,'Neha Singh','Pune','neha@gmail.com'),
(107,'Vikram Gupta','Delhi','vikram@gmail.com'),
(108,'Anjali Verma','Hyderabad','anjali@gmail.com'),
(109,'Rohan Mehta','Ahmedabad','rohan@gmail.com'),
(110,'Kiran Das','Kolkata','kiran@gmail.com');

CREATE TABLE Products (
    Prod_ID INT PRIMARY KEY,
    Product_Name VARCHAR(100),
    Category VARCHAR(50),
    Price DECIMAL(10,2)
);

INSERT INTO Products VALUES
(201,'Laptop','Electronics',65000),
(202,'Smartphone','Electronics',30000),
(203,'Headphones','Electronics',2500),
(204,'Office Chair','Furniture',7000),
(205,'Study Table','Furniture',12000),
(206,'Running Shoes','Fashion',3500),
(207,'Backpack','Fashion',1800),
(208,'Smart Watch','Electronics',5500),
(209,'Water Bottle','Accessories',500),
(210,'Bluetooth Speaker','Electronics',4000);

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Cust_ID INT,
    Order_Date DATE,
    Status VARCHAR(20),
    FOREIGN KEY (Cust_ID) REFERENCES Customers(Cust_ID)
);

INSERT INTO Orders VALUES
(301,101,'2025-01-05','Delivered'),
(302,102,'2025-01-12','Delivered'),
(303,103,'2025-01-18','Pending'),
(304,104,'2025-02-02','Delivered'),
(305,105,'2025-02-10','Cancelled'),
(306,106,'2025-02-15','Delivered'),
(307,107,'2025-03-01','Delivered'),
(308,108,'2025-03-05','Pending'),
(309,109,'2025-03-12','Delivered'),
(310,110,'2025-03-20','Delivered'),
(311,101,'2025-04-01','Delivered'),
(312,102,'2025-04-08','Pending'),
(313,103,'2025-04-15','Delivered'),
(314,104,'2025-05-01','Delivered'),
(315,105,'2025-05-10','Cancelled'),
(316,106,'2025-05-18','Delivered'),
(317,107,'2025-05-25','Pending'),
(318,108,'2025-06-02','Delivered');

CREATE TABLE OrderDetails (
    Detail_ID INT PRIMARY KEY,
    Order_ID INT,
    Prod_ID INT,
    Quantity INT,
    FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID),
    FOREIGN KEY (Prod_ID) REFERENCES Products(Prod_ID)
);

INSERT INTO OrderDetails VALUES
(1,301,201,1),
(2,301,203,2),
(3,302,202,1),
(4,302,209,3),
(5,303,204,1),
(6,304,205,1),
(7,304,207,2),
(8,305,206,1),
(9,306,208,1),
(10,306,209,2),
(11,307,201,1),
(12,308,210,2),
(13,309,202,1),
(14,309,203,1),
(15,310,207,3),
(16,311,204,2),
(17,312,205,1),
(18,313,208,2),
(19,313,209,4),
(20,314,201,1),
(21,314,210,1),
(22,315,206,2),
(23,316,202,1),
(24,316,207,1),
(25,317,203,3),
(26,317,209,2),
(27,318,208,1),
(28,318,210,2),
(29,318,207,1),
(30,310,209,5);

SELECT * FROM Customers;
SELECT * FROM Products;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;

/* ==========================================
   CUSTOMER ANALYSIS
   ========================================== */

-- Total number of customers
SELECT COUNT(Cust_ID) AS Total_Customers
FROM Customers;

-- Number of customers in each city
SELECT City, COUNT(Cust_ID) AS Customer_Count
FROM Customers
GROUP BY City;

-- Orders placed by each customer
SELECT c.Name,
       COUNT(o.Order_ID) AS Total_Orders
FROM Customers c
JOIN Orders o
ON c.Cust_ID = o.Cust_ID
GROUP BY c.Name;

-- Customer with highest spending
SELECT c.Name,
       SUM(p.Price * od.Quantity) AS Total_Spending
FROM Customers c
JOIN Orders o
ON c.Cust_ID = o.Cust_ID
JOIN OrderDetails od
ON o.Order_ID = od.Order_ID
JOIN Products p
ON od.Prod_ID = p.Prod_ID
GROUP BY c.Cust_ID, c.Name
ORDER BY Total_Spending DESC
LIMIT 1;


/* ==========================================
   PRODUCT ANALYSIS
   ========================================== */

-- Most expensive product
SELECT *
FROM Products
ORDER BY Price DESC
LIMIT 1;

-- Cheapest product
SELECT *
FROM Products
ORDER BY Price ASC
LIMIT 1;

-- Total quantity sold for each product
SELECT p.Product_Name,
       SUM(od.Quantity) AS Total_Sold
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID
GROUP BY p.Product_Name;

-- Best-selling product
SELECT p.Product_Name,
       SUM(od.Quantity) AS Total_Sold
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID
GROUP BY p.Product_Name
ORDER BY Total_Sold DESC
LIMIT 1;

-- Revenue generated by each product
SELECT p.Product_Name,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID
GROUP BY p.Product_Name;


/* ==========================================
   ORDER ANALYSIS
   ========================================== */

-- Total number of orders
SELECT COUNT(*) AS Total_Orders
FROM Orders;

-- Number of Delivered, Pending and Cancelled orders
SELECT Status,
       COUNT(*) AS Order_Count
FROM Orders
GROUP BY Status;

-- Latest order placed
SELECT *
FROM Orders
ORDER BY Order_Date DESC
LIMIT 1;


/* ==========================================
   REVENUE ANALYSIS
   ========================================== */

-- Total revenue generated
SELECT SUM(p.Price * od.Quantity) AS Total_Revenue
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID;

-- Revenue generated by each customer
SELECT c.Name,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Customers c
JOIN Orders o
ON c.Cust_ID = o.Cust_ID
JOIN OrderDetails od
ON o.Order_ID = od.Order_ID
JOIN Products p
ON od.Prod_ID = p.Prod_ID
GROUP BY c.Name;

-- Revenue generated by each category
SELECT p.Category,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID
GROUP BY p.Category;

-- Monthly revenue trend
SELECT MONTH(o.Order_Date) AS Month_No,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Orders o
JOIN OrderDetails od
ON o.Order_ID = od.Order_ID
JOIN Products p
ON od.Prod_ID = p.Prod_ID
GROUP BY MONTH(o.Order_Date)
ORDER BY Month_No;


/* ==========================================
   JOIN & GROUP BY DEMONSTRATION
   ========================================== */

-- Customer name with order details
SELECT c.Name,
       o.Order_ID,
       o.Order_Date,
       o.Status
FROM Customers c
JOIN Orders o
ON c.Cust_ID = o.Cust_ID;

-- Order ID with total order amount
SELECT o.Order_ID,
       SUM(p.Price * od.Quantity) AS Order_Amount
FROM Orders o
JOIN OrderDetails od
ON o.Order_ID = od.Order_ID
JOIN Products p
ON od.Prod_ID = p.Prod_ID
GROUP BY o.Order_ID;

-- Products with total sales quantity
SELECT p.Product_Name,
       SUM(od.Quantity) AS Total_Sales
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID
GROUP BY p.Product_Name;


/* ==========================================
   BONUS QUERIES (RECOMMENDED)
   ========================================== */

-- Top 3 spending customers
SELECT c.Name,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Customers c
JOIN Orders o ON c.Cust_ID = o.Cust_ID
JOIN OrderDetails od ON o.Order_ID = od.Order_ID
JOIN Products p ON od.Prod_ID = p.Prod_ID
GROUP BY c.Name
ORDER BY Revenue DESC
LIMIT 3;

-- Product generating highest revenue
SELECT p.Product_Name,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Products p
JOIN OrderDetails od
ON p.Prod_ID = od.Prod_ID
GROUP BY p.Product_Name
ORDER BY Revenue DESC
LIMIT 1;

-- Month with highest revenue
SELECT MONTH(o.Order_Date) AS Month_No,
       SUM(p.Price * od.Quantity) AS Revenue
FROM Orders o
JOIN OrderDetails od ON o.Order_ID = od.Order_ID
JOIN Products p ON od.Prod_ID = p.Prod_ID
GROUP BY MONTH(o.Order_Date)
ORDER BY Revenue DESC
LIMIT 1;


